const $=id=>document.getElementById(id), LS='tradelab_positions_v3', LSSET='tradelab_cost_settings_v1', OLD='tradelab_trades_v2';
const defaultSettings={twFeePct:0.1425,twDiscount:1,twMinFee:0,twTaxPct:0.3,twDayTaxPct:0.15,usFixedFee:0,usSellRatePct:0};
let settings=Object.assign({},defaultSettings,JSON.parse(localStorage.getItem(LSSET)||'{}'));
const db=[['2330','台積電','TW','TWSE'],['2454','聯發科','TW','TWSE'],['2317','鴻海','TW','TWSE'],['2382','廣達','TW','TWSE'],['3231','緯創','TW','TWSE'],['6669','緯穎','TW','TWSE'],['2308','台達電','TW','TWSE'],['3017','奇鋐','TW','TWSE'],['3035','智原','TW','TWSE'],['3443','創意','TW','TWSE'],['3661','世芯-KY','TW','TWSE'],['2376','技嘉','TW','TWSE'],['2357','華碩','TW','TWSE'],['2379','瑞昱','TW','TWSE'],['3711','日月光投控','TW','TWSE'],['2345','智邦','TW','TWSE'],['2059','川湖','TW','TWSE'],['3324','雙鴻','TW','TPEX'],['8299','群聯','TW','TPEX'],['NVDA','NVIDIA','US','NASDAQ'],['MSFT','Microsoft','US','NASDAQ'],['AVGO','Broadcom','US','NASDAQ'],['AMD','AMD','US','NASDAQ'],['AAPL','Apple','US','NASDAQ'],['GOOGL','Alphabet','US','NASDAQ'],['META','Meta Platforms','US','NASDAQ'],['AMZN','Amazon','US','NASDAQ'],['TSLA','Tesla','US','NASDAQ'],['PLTR','Palantir','US','NASDAQ'],['CRWD','CrowdStrike','US','NASDAQ'],['NOW','ServiceNow','US','NYSE'],['MU','Micron','US','NASDAQ'],['ARM','Arm Holdings','US','NASDAQ'],['SMCI','Super Micro Computer','US','NASDAQ'],['ANET','Arista Networks','US','NYSE']].map(x=>({symbol:x[0],name:x[1],market:x[2],exchange:x[3]}));
const watch={US:db.filter(x=>['NVDA','MSFT','AVGO','AMD','PLTR','CRWD','NOW','ANET'].includes(x.symbol)),TW:db.filter(x=>['2330','2454','2317','2382','3231','6669','2308','3017','3035','3443','3661'].includes(x.symbol))};
let positions=JSON.parse(localStorage.getItem(LS)||'null');
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function n(v){v=parseFloat(v);return Number.isFinite(v)?v:null}
function save(){localStorage.setItem(LS,JSON.stringify(positions))}
function saveSettings(){localStorage.setItem(LSSET,JSON.stringify(settings))}
function migrate(){if(Array.isArray(positions))return;positions=[];let old=[];try{old=JSON.parse(localStorage.getItem(OLD)||'[]')}catch{};for(const t of old){let p={id:uid(),market:t.market,ticker:t.ticker,name:t.name||'',setup:t.setup||'其他',stop:t.stop,reason:t.reason||'',review:t.review||'',legs:[]};if(t.buyAt&&n(t.buy)!=null&&n(t.qty)!=null)p.legs.push({id:uid(),type:'BUY',at:t.buyAt,price:n(t.buy),qty:n(t.qty),fee:n(t.fee)||0,tax:0,daytrade:false});if(t.sellAt&&n(t.sell)!=null&&n(t.qty)!=null)p.legs.push({id:uid(),type:'SELL',at:t.sellAt,price:n(t.sell),qty:n(t.qty),fee:0,tax:0,daytrade:false});positions.push(p)}save()}
migrate();
function money(v,m){if(!Number.isFinite(v))return'—';return new Intl.NumberFormat('zh-TW',{style:'currency',currency:m==='TW'?'TWD':'USD',maximumFractionDigits:2}).format(v)}
function pct(v){return Number.isFinite(v)?(v>=0?'+':'')+v.toFixed(2)+'%':'—'}
function cls(v){return v>0?'good':v<0?'bad':''}
function fmtQty(q,m){if(!Number.isFinite(q))return'—';if(m==='TW'&&q>=1000&&q%1000===0)return(q/1000).toLocaleString()+' 張';return q.toLocaleString()+' 股'}
function tradeCost(m,type,amount,daytrade,manualFee,manualTax){let fee=0,tax=0;if(m==='TW'){fee=Math.max(settings.twMinFee||0,amount*(settings.twFeePct/100)*(settings.twDiscount||0));tax=type==='SELL'?amount*((daytrade?settings.twDayTaxPct:settings.twTaxPct)/100):0}else{fee=settings.usFixedFee||0;tax=type==='SELL'?amount*(settings.usSellRatePct/100):0}if(Number.isFinite(manualFee))fee=manualFee;if(Number.isFinite(manualTax))tax=manualTax;return{fee,tax}}
function summarize(p){let legs=[...p.legs].sort((a,b)=>new Date(a.at)-new Date(b.at)),qty=0,avg=0,realized=0,totalFees=0,totalTax=0,totalBought=0,totalSold=0;for(const l of legs){totalFees+=n(l.fee)||0;totalTax+=n(l.tax)||0;if(l.type==='BUY'){let q=n(l.qty)||0,price=n(l.price)||0;avg=(qty*avg+q*price)/(qty+q||1);qty+=q;totalBought+=q}else{let q=Math.min(n(l.qty)||0,qty),price=n(l.price)||0;realized+=(price-avg)*q-(n(l.fee)||0)-(n(l.tax)||0);qty-=q;totalSold+=q;if(qty<=0){qty=0;avg=0}}}let buyFees=legs.filter(x=>x.type==='BUY').reduce((s,x)=>s+(n(x.fee)||0),0);realized-=buyFees*(totalBought?Math.min(1,totalSold/totalBought):0);let invested=legs.filter(x=>x.type==='BUY').reduce((s,x)=>s+(n(x.price)||0)*(n(x.qty)||0),0);let ret=invested?realized/invested*100:null;return{qty,avg,realized,totalFees,totalTax,totalCost:totalFees+totalTax,totalBought,totalSold,open:qty>0,closed:qty===0&&totalBought>0,ret}}
function findOpen(m,ticker,excludeId=''){return positions.find(p=>p.id!==excludeId&&p.market===m&&p.ticker===ticker&&summarize(p).open)}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.p===id));if(id==='dash')dash();if(id==='positions')renderPositions();if(id==='log')log();if(id==='watch')renderWatch()}
document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>go(b.dataset.p));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{resetForm();go(b.dataset.go)});
function dash(){let sums=positions.map(p=>({p,s:summarize(p)})),closed=sums.filter(x=>x.s.closed),wins=closed.filter(x=>x.s.realized>0),tw=sums.filter(x=>x.p.market==='TW').reduce((a,x)=>a+x.s.realized,0),us=sums.filter(x=>x.p.market==='US').reduce((a,x)=>a+x.s.realized,0),cost=sums.reduce((a,x)=>a+x.s.totalCost,0);$('kN').textContent=closed.length;$('kW').textContent=closed.length?(wins.length/closed.length*100).toFixed(1)+'%':'—';$('kTW').textContent=money(tw,'TW');$('kUS').textContent=money(us,'US');$('kOpen').textContent=sums.filter(x=>x.s.open).length;$('kCost').textContent=cost.toFixed(2);let g={};closed.forEach(x=>(g[x.p.setup||'其他']??=[]).push(x));$('setups').innerHTML=Object.entries(g).map(([k,a])=>{let av=a.reduce((s,x)=>s+(x.s.ret||0),0)/a.length,wr=a.filter(x=>x.s.realized>0).length/a.length*100;return`<div class="mb"><small>${k}</small><b class="${cls(av)}">${pct(av)}</b><div class="muted">${a.length} 個部位｜勝率 ${wr.toFixed(0)}%</div></div>`}).join('')||'<div class="muted">完整平倉後自動統計。</div>'}
function renderPositions(){let arr=[...positions].sort((a,b)=>new Date(b.legs.at(-1)?.at||0)-new Date(a.legs.at(-1)?.at||0));$('positionList').innerHTML=arr.length?arr.map(p=>{let s=summarize(p),id=p.id;return`<div class="card position-card"><div class="pos-head"><div class="pos-main"><b>${p.ticker} ${p.name||''}</b><span class="badge ${s.open?'open':'closed'}">${s.open?'持倉中':'已平倉'}</span><div class="muted">${p.market==='TW'?'台股':'美股'} · ${p.setup||'其他'}</div></div><div class="metric"><small>累計買進</small><b>${fmtQty(s.totalBought,p.market)}</b></div><div class="metric"><small>累計賣出</small><b>${fmtQty(s.totalSold,p.market)}</b></div><div class="metric"><small>目前持有</small><b>${fmtQty(s.qty,p.market)}</b></div><div class="metric"><small>平均買價</small><b>${s.avg?s.avg.toFixed(2):'—'}</b></div><div class="metric"><small>已實現損益</small><b class="${cls(s.realized)}">${money(s.realized,p.market)}</b></div><div class="metric"><small>交易成本</small><b>${money(s.totalCost,p.market)}</b></div><div class="pos-actions"><button class="btn small" onclick="toggleLegs('${id}')">展開明細</button>${s.open?`<button class="btn small primary" onclick="prefill('${id}','BUY')">＋加碼</button><button class="btn small sell" onclick="prefill('${id}','SELL')">－賣出</button>`:''}</div></div><div class="legs" id="legs-${id}"><div class="legs-head">每一筆成交都保留，可單獨編輯或刪除。</div><div class="tablewrap" style="max-height:none"><table><thead><tr><th>日期</th><th>動作</th><th>數量</th><th>價格</th><th>成交額</th><th>手續費</th><th>稅費</th><th>操作</th></tr></thead><tbody>${[...p.legs].sort((a,b)=>new Date(a.at)-new Date(b.at)).map(l=>`<tr><td>${l.at?.replace('T',' ')||'—'}</td><td class="${l.type==='BUY'?'leg-buy':'leg-sell'}">${l.type==='BUY'?'買進':'賣出'}</td><td>${fmtQty(l.qty,p.market)}</td><td>${l.price}</td><td>${money((l.price||0)*(l.qty||0),p.market)}</td><td>${money(l.fee||0,p.market)}</td><td>${money(l.tax||0,p.market)}</td><td><button class="btn small" onclick="editLeg('${id}','${l.id}')">編輯</button> <button class="btn small" onclick="deleteLeg('${id}','${l.id}')">刪除</button></td></tr>`).join('')}</tbody></table></div></div></div>`}).join(''):'<div class="card panel muted">尚未有交易。</div>'}
window.toggleLegs=id=>$('legs-'+id).classList.toggle('show');
function resetForm(){['editPos','editLeg','stockq','name','ticker','tradeAt','price','qty','stop','reason','review','manualFee','manualTax'].forEach(id=>$(id).value='');$('action').value='BUY';$('market').value='TW';$('qtyUnit').value='LOT';$('setup').value='VCP';$('daytrade').value='no';$('feeMode').value='auto';$('formTitle').textContent='新增成交';updatePreview()}
window.prefill=(pid,type)=>{let p=positions.find(x=>x.id===pid);if(!p)return;resetForm();$('editPos').value=pid;$('action').value=type;$('market').value=p.market;$('ticker').value=p.ticker;$('name').value=p.name||'';$('stockq').value=p.name+' '+p.ticker;$('setup').value=p.setup||'其他';$('stop').value=p.stop??'';$('qtyUnit').value=p.market==='TW'?'LOT':'SHARE';$('formTitle').textContent=(type==='BUY'?'加碼':'賣出')+'｜'+p.ticker+' '+(p.name||'');go('new');updatePreview()};
window.editLeg=(pid,lid)=>{let p=positions.find(x=>x.id===pid),l=p?.legs.find(x=>x.id===lid);if(!p||!l)return;resetForm();$('editPos').value=pid;$('editLeg').value=lid;$('action').value=l.type;$('market').value=p.market;$('ticker').value=p.ticker;$('name').value=p.name||'';$('stockq').value=p.name+' '+p.ticker;$('tradeAt').value=l.at||'';$('price').value=l.price??'';if(p.market==='TW'&&l.qty%1000===0){$('qty').value=l.qty/1000;$('qtyUnit').value='LOT'}else{$('qty').value=l.qty;$('qtyUnit').value='SHARE'}$('setup').value=p.setup||'其他';$('stop').value=p.stop??'';$('reason').value=p.reason||'';$('review').value=p.review||'';$('daytrade').value=l.daytrade?'yes':'no';$('feeMode').value='manual';$('manualFee').value=l.fee??0;$('manualTax').value=l.tax??0;$('formTitle').textContent='編輯成交｜'+p.ticker;go('new');updatePreview()};
window.deleteLeg=(pid,lid)=>{if(!confirm('刪除這筆成交？'))return;let p=positions.find(x=>x.id===pid);p.legs=p.legs.filter(x=>x.id!==lid);if(!p.legs.length)positions=positions.filter(x=>x.id!==pid);save();renderPositions();dash();log()};
function renderSug(q){q=q.trim().toLowerCase();if(!q){$('sug').classList.remove('show');return}let a=db.filter(x=>x.symbol.toLowerCase().includes(q)||x.name.toLowerCase().includes(q)).slice(0,12);$('sug').innerHTML=a.map((x,i)=>`<div class="srow" data-i="${i}"><b>${x.symbol}</b>${x.name}<br><small>${x.exchange} · ${x.market==='TW'?'台股':'美股'}</small></div>`).join('')||'<div class="srow"><small>找不到候選，可直接輸入代號。</small></div>';$('sug').classList.add('show');[...$('sug').querySelectorAll('[data-i]')].forEach((el,i)=>el.onclick=()=>{let x=a[i];$('market').value=x.market;$('ticker').value=x.symbol;$('name').value=x.name;$('stockq').value=x.name+' '+x.symbol;$('qtyUnit').value=x.market==='TW'?'LOT':'SHARE';$('sug').classList.remove('show');updatePreview()})}
$('stockq').oninput=e=>renderSug(e.target.value);document.addEventListener('click',e=>{if(!e.target.closest('.searchwrap'))$('sug').classList.remove('show')});
function enteredQty(){let q=n($('qty').value);if(!Number.isFinite(q))return null;return $('market').value==='TW'&&$('qtyUnit').value==='LOT'?q*1000:q}
function updatePreview(){let m=$('market').value,type=$('action').value,price=n($('price').value),q=enteredQty(),amount=price&&q?price*q:null,manual=$('feeMode').value==='manual',mf=manual?n($('manualFee').value):null,mt=manual?n($('manualTax').value):null,c=amount?tradeCost(m,type,amount,$('daytrade').value==='yes',mf,mt):{fee:null,tax:null};$('pvAmount').textContent=amount?money(amount,m):'—';$('pvFee').textContent=Number.isFinite(c.fee)?money(c.fee,m):'—';$('pvTax').textContent=Number.isFinite(c.tax)?money(c.tax,m):'—';$('pvCost').textContent=Number.isFinite(c.fee)&&Number.isFinite(c.tax)?money(c.fee+c.tax,m):'—';let p=findOpen(m,$('ticker').value.trim().toUpperCase(),$('editPos').value),cur=p?summarize(p).qty:0;if($('editPos').value){let ep=positions.find(x=>x.id===$('editPos').value);if(ep){let es=summarize(ep);cur=es.qty;if($('editLeg').value){let old=ep.legs.find(x=>x.id===$('editLeg').value);if(old)cur+=old.type==='BUY'?-old.qty:old.qty}}}if(Number.isFinite(q))cur+=type==='BUY'?q:-q;$('pvRemain').textContent=fmtQty(Math.max(0,cur),m)}
['market','action','price','qty','qtyUnit','daytrade','feeMode','manualFee','manualTax','ticker'].forEach(id=>$(id).addEventListener(id==='price'||id==='qty'||id==='manualFee'||id==='manualTax'||id==='ticker'?'input':'change',updatePreview));
$('form').onsubmit=e=>{e.preventDefault();let m=$('market').value,ticker=$('ticker').value.trim().toUpperCase(),name=$('name').value.trim(),type=$('action').value,at=$('tradeAt').value,price=n($('price').value),qty=enteredQty();if(!ticker||!at||!price||!qty)return alert('請完整填寫股票、日期、價格與數量');let pid=$('editPos').value,lid=$('editLeg').value,p=pid?positions.find(x=>x.id===pid):findOpen(m,ticker);if(!p){if(type==='SELL')return alert('找不到可賣出的持倉，請先建立買進成交。');p={id:uid(),market:m,ticker,name,setup:$('setup').value,stop:n($('stop').value),reason:$('reason').value,review:$('review').value,legs:[]};positions.push(p)}else{p.name=name||p.name;p.setup=$('setup').value||p.setup;p.stop=n($('stop').value);p.reason=$('reason').value||p.reason;p.review=$('review').value||p.review}if(type==='SELL'){let s=summarize(p),available=s.qty;if(lid){let old=p.legs.find(x=>x.id===lid);if(old&&old.type==='SELL')available+=old.qty}if(qty>available+1e-9)return alert('賣出數量超過目前持有數量：'+fmtQty(available,m))}let amount=price*qty,manual=$('feeMode').value==='manual',c=tradeCost(m,type,amount,$('daytrade').value==='yes',manual?n($('manualFee').value):null,manual?n($('manualTax').value):null),leg={id:lid||uid(),type,at,price,qty,fee:c.fee,tax:c.tax,daytrade:$('daytrade').value==='yes'};if(lid){let i=p.legs.findIndex(x=>x.id===lid);p.legs[i]=leg}else p.legs.push(leg);save();resetForm();renderPositions();dash();log();go('positions')};
$('clear').onclick=resetForm;
function log(){let q=$('filter').value.toLowerCase(),all=[];positions.forEach(p=>p.legs.forEach(l=>all.push({p,l})));all.sort((a,b)=>new Date(b.l.at)-new Date(a.l.at));all=all.filter(x=>[x.p.ticker,x.p.name,x.p.setup,x.p.reason,x.p.review].join(' ').toLowerCase().includes(q));$('rows').innerHTML=all.map(({p,l})=>`<tr><td>${l.at?.replace('T',' ')||'—'}</td><td>${p.market}</td><td><b>${p.ticker}</b> ${p.name||''}</td><td class="${l.type==='BUY'?'leg-buy':'leg-sell'}">${l.type==='BUY'?'買進':'賣出'}</td><td>${fmtQty(l.qty,p.market)}</td><td>${l.price}</td><td>${money(l.price*l.qty,p.market)}</td><td>${money(l.fee||0,p.market)}</td><td>${money(l.tax||0,p.market)}</td><td><button class="btn small" onclick="editLeg('${p.id}','${l.id}')">編輯</button> <button class="btn small" onclick="deleteLeg('${p.id}','${l.id}')">刪除</button></td></tr>`).join('')||'<tr><td colspan="10" class="muted">沒有成交紀錄。</td></tr>'}
$('filter').oninput=log;
function renderWatch(){['US','TW'].forEach(m=>{$(m==='US'?'usw':'tww').innerHTML=watch[m].map((x,i)=>`<div class="witem" onclick="detail('${m}',${i})"><div class="wtop"><div><span class="ticker">${x.symbol}</span> <span class="muted">${x.name}</span></div><span class="tag">${x.exchange}</span></div><div class="note">點擊查看 K 線、成交量、技術分析與基本面。</div></div>`).join('')})}
function tvsym(x){return(x.exchange||'NASDAQ')+':'+x.symbol}function widget(id,src,cfg){let b=$(id);b.innerHTML='<div class="tradingview-widget-container__widget" style="height:100%;width:100%"></div>';let s=document.createElement('script');s.src=src;s.async=true;s.text=JSON.stringify(cfg);b.appendChild(s)}
window.detail=(m,i)=>{let x=watch[m][i];$('mt').textContent=x.symbol;$('mn').textContent=x.name;$('stockModal').classList.add('show');document.body.style.overflow='hidden';document.querySelectorAll('#stockModal .tabs button').forEach((b,j)=>b.classList.toggle('on',j===0));document.querySelectorAll('#stockModal .tabp').forEach((p,j)=>p.classList.toggle('on',j===0));let s=tvsym(x);widget('tvchart','https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js',{autosize:true,symbol:s,interval:'D',timezone:'Asia/Taipei',theme:'dark',style:'1',locale:'zh_TW',allow_symbol_change:true,hide_side_toolbar:false,withdateranges:true,studies:['STD;Volume','STD;SMA']});widget('tvtech','https://s3.tradingview.com/external-embedding/embed-widget-technical-analysis.js',{interval:'1D',width:'100%',height:'100%',symbol:s,showIntervalTabs:true,displayMode:'multiple',locale:'zh_TW',colorTheme:'dark',isTransparent:true});widget('tvprofile','https://s3.tradingview.com/external-embedding/embed-widget-company-profile.js',{width:'100%',height:'100%',symbol:s,locale:'zh_TW',colorTheme:'dark',isTransparent:true});widget('tvfund','https://s3.tradingview.com/external-embedding/embed-widget-financials.js',{width:'100%',height:'100%',symbol:s,locale:'zh_TW',colorTheme:'dark',isTransparent:true})};
$('mclose').onclick=()=>{$('stockModal').classList.remove('show');document.body.style.overflow=''};document.querySelectorAll('#stockModal .tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#stockModal .tabs button').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('#stockModal .tabp').forEach(x=>x.classList.toggle('on',x.id==='tab-'+b.dataset.tab))});
function openSettings(){$('setTwFee').value=settings.twFeePct;$('setTwDiscount').value=settings.twDiscount;$('setTwMin').value=settings.twMinFee;$('setTwTax').value=settings.twTaxPct;$('setTwDayTax').value=settings.twDayTaxPct;$('setUsFee').value=settings.usFixedFee;$('setUsSellRate').value=settings.usSellRatePct;$('settingsModal').classList.add('show')}
$('settingsBtn').onclick=openSettings;$('settingsClose').onclick=()=>$('settingsModal').classList.remove('show');$('settingsSave').onclick=()=>{settings={twFeePct:n($('setTwFee').value)??defaultSettings.twFeePct,twDiscount:n($('setTwDiscount').value)??1,twMinFee:n($('setTwMin').value)??0,twTaxPct:n($('setTwTax').value)??defaultSettings.twTaxPct,twDayTaxPct:n($('setTwDayTax').value)??defaultSettings.twDayTaxPct,usFixedFee:n($('setUsFee').value)??0,usSellRatePct:n($('setUsSellRate').value)??0};saveSettings();$('settingsModal').classList.remove('show');updatePreview();alert('交易成本設定已儲存')};
$('backup').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({positions,settings},null,2)],{type:'application/json'}));a.download='TradeLab_backup.json';a.click()};
resetForm();dash();renderPositions();renderWatch();log();