(()=>{
const oldDetail=window.detail;
const $=id=>document.getElementById(id);
function twseDate(s){const p=String(s).split('/');if(p.length!==3)return s;return `${Number(p[0])+1911}-${p[1].padStart(2,'0')}-${p[2].padStart(2,'0')}`}
function num(s){if(s==null)return null;const v=Number(String(s).replaceAll(',','').replace('--',''));return Number.isFinite(v)?v:null}
function monthKeys(n=12){const out=[],d=new Date();for(let i=0;i<n;i++){const x=new Date(d.getFullYear(),d.getMonth()-i,1);out.push(`${x.getFullYear()}${String(x.getMonth()+1).padStart(2,'0')}01`)}return out.reverse()}
async function fetchTwse(symbol){const all=[];for(const date of monthKeys(12)){try{const u=`https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=${date}&stockNo=${encodeURIComponent(symbol)}&response=json`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)continue;const d=await r.json();if(!Array.isArray(d.data))continue;for(const a of d.data){const row={date:twseDate(a[0]),volume:num(a[1]),open:num(a[3]),high:num(a[4]),low:num(a[5]),close:num(a[6])};if([row.open,row.high,row.low,row.close].every(Number.isFinite))all.push(row)}}catch(e){}}
const m=new Map();all.forEach(x=>m.set(x.date,x));return [...m.values()].sort((a,b)=>a.date.localeCompare(b.date))}
function ma(data,n){return data.map((x,i)=>{if(i<n-1)return null;let s=0;for(let j=i-n+1;j<=i;j++)s+=data[j].close;return s/n})}
function drawChart(data,symbol,name){const host=$('tvchart');host.innerHTML=`<div style="height:100%;display:flex;flex-direction:column"><div style="padding:10px 12px;border-bottom:1px solid #243a55;display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><div><b>${symbol} ${name||''}</b> <span style="color:#91a4bd;font-size:12px">TWSE 日K｜近12個月</span></div><div style="font-size:11px;color:#91a4bd">資料：臺灣證券交易所</div></div><canvas id="twCanvas" style="flex:1;min-height:520px;width:100%"></canvas></div>`;
const c=$('twCanvas'),ctx=c.getContext('2d');const rect=host.getBoundingClientRect();const W=Math.max(900,rect.width),H=Math.max(560,rect.height-48),dpr=window.devicePixelRatio||1;c.width=W*dpr;c.height=H*dpr;c.style.height=H+'px';ctx.scale(dpr,dpr);
const left=58,right=18,top=25,bottom=28,volH=120,gap=22,priceH=H-top-bottom-volH-gap;const view=data.slice(-180);const highs=view.map(x=>x.high),lows=view.map(x=>x.low),max=Math.max(...highs),min=Math.min(...lows),pad=(max-min)*.06||1,pMax=max+pad,pMin=min-pad;const maxVol=Math.max(...view.map(x=>x.volume||0),1);const xstep=(W-left-right)/view.length;const y=v=>top+(pMax-v)/(pMax-pMin)*priceH;ctx.fillStyle='#0a111b';ctx.fillRect(0,0,W,H);ctx.font='11px system-ui';ctx.strokeStyle='#1d2b3d';ctx.fillStyle='#8fa3ba';for(let i=0;i<=5;i++){const yy=top+i*priceH/5,val=pMax-i*(pMax-pMin)/5;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(W-right,yy);ctx.stroke();ctx.fillText(val.toFixed(2),5,yy+4)}
const ma20=ma(view,20),ma50=ma(view,50);function line(arr,color){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();let started=false;arr.forEach((v,i)=>{if(!Number.isFinite(v))return;const xx=left+(i+.5)*xstep,yy=y(v);if(!started){ctx.moveTo(xx,yy);started=true}else ctx.lineTo(xx,yy)});ctx.stroke()}line(ma20,'#f4ca63');line(ma50,'#6ea8fe');
view.forEach((d,i)=>{const xx=left+(i+.5)*xstep,up=d.close>=d.open,color=up?'#ff5d73':'#55d6b2';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(xx,y(d.high));ctx.lineTo(xx,y(d.low));ctx.stroke();const bw=Math.max(2,xstep*.62),yy=y(Math.max(d.open,d.close)),hh=Math.max(1,Math.abs(y(d.open)-y(d.close)));ctx.fillRect(xx-bw/2,yy,bw,hh);const vh=(d.volume||0)/maxVol*volH,vy=top+priceH+gap+(volH-vh);ctx.globalAlpha=.65;ctx.fillRect(xx-bw/2,vy,bw,vh);ctx.globalAlpha=1});
ctx.fillStyle='#f4ca63';ctx.fillText('MA20',left+8,16);ctx.fillStyle='#6ea8fe';ctx.fillText('MA50',left+55,16);ctx.fillStyle='#8fa3ba';ctx.fillText('成交量',5,top+priceH+gap+14);if(view.length){ctx.fillText(view[0].date,left,H-7);ctx.textAlign='right';ctx.fillText(view.at(-1).date,W-right,H-7);ctx.textAlign='left'}}
function renderTech(data){const el=$('tvtech');if(!data.length){el.innerHTML='<div class="panel muted">沒有可計算的行情資料。</div>';return}const closes=data.map(x=>x.close),last=closes.at(-1),hi=Math.max(...closes.slice(-250)),lo=Math.min(...closes.slice(-250));const avg=n=>closes.length>=n?closes.slice(-n).reduce((a,b)=>a+b,0)/n:null;const m20=avg(20),m50=avg(50),m150=avg(150),m200=avg(200);const boxes=[['最新收盤',last?.toFixed(2)],['20日均線',m20?.toFixed(2)||'—'],['50日均線',m50?.toFixed(2)||'—'],['150日均線',m150?.toFixed(2)||'—'],['200日均線',m200?.toFixed(2)||'—'],['距52週高',hi?((last/hi-1)*100).toFixed(1)+'%':'—'],['52週區間位置',hi>lo?((last-lo)/(hi-lo)*100).toFixed(0)+'%':'—'],['趨勢',last>m50&&m50>m150?'偏多':'待觀察']];el.innerHTML=`<div style="padding:18px"><div class="mini">${boxes.map(x=>`<div class="mb"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div><div class="foot">這裡改用證交所行情計算，避免 TradingView 台股嵌入限制。</div></div>`}
function renderFund(x){$('tvprofile').innerHTML=`<div class="panel"><h3>${x.symbol} ${x.name}</h3><p class="muted">台股基本面頁面改用外部可靠來源，避免 TradingView Widget 顯示「僅在 TradingView 上可用」。</p><p><button class="btn" onclick="window.open('https://goodinfo.tw/tw/StockDetail.asp?STOCK_ID=${x.symbol}','_blank')">Goodinfo</button> <button class="btn" onclick="window.open('https://tw.stock.yahoo.com/quote/${x.symbol}.TW','_blank')">Yahoo 股市</button> <button class="btn" onclick="window.open('https://www.tradingview.com/symbols/TWSE-${x.symbol}/','_blank')">TradingView 主站</button></p></div>`;$('tvfund').innerHTML=`<div class="panel"><h3>籌碼 / 法人</h3><p><button class="btn" onclick="window.open('https://www.wantgoo.com/stock/${x.symbol}/major-investors/main-trend','_blank')">玩股網籌碼</button></p><p class="muted">之後可再把三大法人、融資融券等資料直接整合進 TradeLab。</p></div>`}
window.detail=async(m,i)=>{if(m!=='TW')return oldDetail(m,i);const x=watch[m][i];$('mt').textContent=x.symbol;$('mn').textContent=x.name;$('stockModal').classList.add('show');document.body.style.overflow='hidden';document.querySelectorAll('#stockModal .tabs button').forEach((b,j)=>b.classList.toggle('on',j===0));document.querySelectorAll('#stockModal .tabp').forEach((p,j)=>p.classList.toggle('on',j===0));$('tvchart').innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">正在讀取證交所 K 線資料…</div>';$('tvtech').innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">正在計算技術面…</div>';renderFund(x);const data=await fetchTwse(x.symbol);if(!data.length){$('tvchart').innerHTML=`<div class="panel" style="margin:20px"><h3>目前無法取得 ${x.symbol} 行情</h3><p class="muted">可能是證交所暫時限制跨站請求。你仍可使用下方外部連結。</p><button class="btn" onclick="window.open('https://tw.stock.yahoo.com/quote/${x.symbol}.TW','_blank')">Yahoo 股市</button> <button class="btn" onclick="window.open('https://www.tradingview.com/symbols/TWSE-${x.symbol}/','_blank')">TradingView 主站</button></div>`;$('tvtech').innerHTML='<div class="panel muted" style="margin:20px">行情資料暫時無法讀取。</div>';return}drawChart(data,x.symbol,x.name);renderTech(data)};
})();