(()=>{
const $=id=>document.getElementById(id);
const C={bg:'#07111f',grid:'#1c3048',text:'#91a4bd',up:'#ff5d73',down:'#55d6b2',ma20:'#f4ca63',ma50:'#6ea8fe',ma100:'#c084fc',ma200:'#f59e0b'};
function yahooSymbol(x){if(x.market!=='TW')return x.symbol;return x.symbol+(x.exchange==='TPEX'?'.TWO':'.TW')}
function fmtDate(ts){return new Date(ts*1000).toLocaleDateString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit'})}
function fmtVol(v){if(!Number.isFinite(v))return'—';if(v>=1e9)return(v/1e9).toFixed(1)+'B';if(v>=1e6)return(v/1e6).toFixed(1)+'M';if(v>=1e3)return(v/1e3).toFixed(1)+'K';return Math.round(v).toLocaleString()}
async function fetchYahoo(x){const s=encodeURIComponent(yahooSymbol(x));const u=`https://query1.finance.yahoo.com/v8/finance/chart/${s}?range=2y&interval=1d&includePrePost=false&events=div%2Csplits`;
 const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('Yahoo HTTP '+r.status);const j=await r.json(),z=j?.chart?.result?.[0];if(!z)throw new Error(j?.chart?.error?.description||'沒有行情');const q=z.indicators.quote[0],a=z.indicators.adjclose?.[0]?.adjclose||[];const out=[];(z.timestamp||[]).forEach((t,i)=>{const d={ts:t,date:fmtDate(t),open:q.open?.[i],high:q.high?.[i],low:q.low?.[i],close:q.close?.[i],volume:q.volume?.[i],adj:a[i]};if([d.open,d.high,d.low,d.close].every(Number.isFinite))out.push(d)});return{data:out,meta:z.meta||{}}}
function moving(data,n){const out=new Array(data.length).fill(null);let sum=0;for(let i=0;i<data.length;i++){sum+=data[i].close;if(i>=n)sum-=data[i-n].close;if(i>=n-1)out[i]=sum/n}return out}
function findLegs(x){try{const p=positions.filter(p=>p.market===x.market&&p.ticker===x.symbol);return p.flatMap(p=>p.legs.map(l=>({type:l.type,at:l.at,price:l.price,qty:l.qty}))) }catch{return[]}}
function renderChart(data,x,meta){const host=$('tvchart');host.innerHTML=`<div style="height:100%;display:flex;flex-direction:column">
 <div style="padding:9px 12px;border-bottom:1px solid #243a55;display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap">
  <div><b>${x.symbol} ${x.name||''}</b> <span class="muted">Yahoo Finance 日K</span></div>
  <div id="chartReadout" style="font-size:12px;color:#b8c7d9">移到 K 棒查看 OHLC</div>
 </div>
 <div style="padding:8px 12px;display:flex;gap:6px;align-items:center;flex-wrap:wrap;border-bottom:1px solid #182b42">
  <button class="btn small range" data-n="22">1月</button><button class="btn small range" data-n="66">3月</button><button class="btn small range" data-n="132">6月</button><button class="btn small range" data-n="264">1年</button><button class="btn small range" data-n="528">2年</button><span class="muted" style="margin-left:8px">滾輪縮放｜按住拖曳｜雙擊重設</span>
  <span style="margin-left:auto;font-size:11px"><b style="color:${C.ma20}">MA20</b>　<b style="color:${C.ma50}">MA50</b>　<b style="color:${C.ma100}">MA100</b>　<b style="color:${C.ma200}">MA200</b></span>
 </div>
 <div style="height:500px;position:relative"><canvas id="priceCanvas" style="width:100%;height:100%;display:block"></canvas></div>
 <div style="height:180px;border-top:1px solid #243a55;position:relative"><div style="position:absolute;left:10px;top:6px;color:#91a4bd;font-size:11px;z-index:2">成交量</div><canvas id="volCanvas" style="width:100%;height:100%;display:block"></canvas></div>
 </div>`;
 const pc=$('priceCanvas'),vc=$('volCanvas'),ro=$('chartReadout'),mas={20:moving(data,20),50:moving(data,50),100:moving(data,100),200:moving(data,200)},legs=findLegs(x);let count=Math.min(132,data.length),end=data.length,drag=false,lastX=0,hover=-1;
 function fit(c){const r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.max(1,Math.floor(r.width*dpr));c.height=Math.max(1,Math.floor(r.height*dpr));const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:r.width,h:r.height}}
 function bounds(){count=Math.max(12,Math.min(count,data.length));end=Math.max(count,Math.min(end,data.length));return{start:end-count,end}}
 function draw(){const P=fit(pc),V=fit(vc),b=bounds(),view=data.slice(b.start,b.end),l=58,r=68,t=20,bt=28,w=P.w-l-r,h=P.h-t-bt;if(!view.length)return;const hi=Math.max(...view.map(d=>d.high)),lo=Math.min(...view.map(d=>d.low)),pd=(hi-lo)*.06||1,max=hi+pd,min=lo-pd,step=w/view.length,y=v=>t+(max-v)/(max-min)*h,xp=i=>l+(i+.5)*step;
 P.ctx.fillStyle=C.bg;P.ctx.fillRect(0,0,P.w,P.h);P.ctx.font='11px system-ui';P.ctx.strokeStyle=C.grid;P.ctx.fillStyle=C.text;for(let i=0;i<=5;i++){const yy=t+i*h/5,val=max-i*(max-min)/5;P.ctx.beginPath();P.ctx.moveTo(l,yy);P.ctx.lineTo(P.w-r,yy);P.ctx.stroke();P.ctx.fillText(val.toFixed(2),P.w-r+7,yy+4)}
 const line=(arr,color)=>{P.ctx.strokeStyle=color;P.ctx.lineWidth=1.5;P.ctx.beginPath();let started=false;for(let gi=b.start;gi<b.end;gi++){const v=arr[gi];if(!Number.isFinite(v))continue;const xx=xp(gi-b.start),yy=y(v);if(!started){P.ctx.moveTo(xx,yy);started=true}else P.ctx.lineTo(xx,yy)}P.ctx.stroke()};line(mas[20],C.ma20);line(mas[50],C.ma50);line(mas[100],C.ma100);line(mas[200],C.ma200);
 view.forEach((d,i)=>{const xx=xp(i),up=d.close>=d.open,col=up?C.up:C.down;P.ctx.strokeStyle=col;P.ctx.fillStyle=col;P.ctx.beginPath();P.ctx.moveTo(xx,y(d.high));P.ctx.lineTo(xx,y(d.low));P.ctx.stroke();const bw=Math.max(2,Math.min(12,step*.65)),yy=y(Math.max(d.open,d.close)),hh=Math.max(1,Math.abs(y(d.open)-y(d.close)));P.ctx.fillRect(xx-bw/2,yy,bw,hh)});
 // 買賣點標記
 for(const leg of legs){const day=(leg.at||'').slice(0,10);const gi=data.findIndex(d=>new Date(d.ts*1000).toISOString().slice(0,10)===day);if(gi<b.start||gi>=b.end)continue;const d=data[gi],xx=xp(gi-b.start),buy=leg.type==='BUY',yy=y(leg.price||d.close);P.ctx.fillStyle=buy?'#22c55e':'#ef4444';P.ctx.beginPath();if(buy){P.ctx.moveTo(xx,yy-13);P.ctx.lineTo(xx-6,yy-3);P.ctx.lineTo(xx+6,yy-3)}else{P.ctx.moveTo(xx,yy+13);P.ctx.lineTo(xx-6,yy+3);P.ctx.lineTo(xx+6,yy+3)}P.ctx.closePath();P.ctx.fill()}
 if(hover>=b.start&&hover<b.end){const i=hover-b.start,xx=xp(i);P.ctx.strokeStyle='#7c8da4';P.ctx.setLineDash([4,4]);P.ctx.beginPath();P.ctx.moveTo(xx,t);P.ctx.lineTo(xx,t+h);P.ctx.stroke();P.ctx.setLineDash([])}
 P.ctx.fillStyle=C.text;P.ctx.fillText(view[0].date,l,P.h-7);P.ctx.textAlign='right';P.ctx.fillText(view.at(-1).date,P.w-r,P.h-7);P.ctx.textAlign='left';
 // volume separately
 const vl=58,vr=68,vt=24,vb=24,vw=V.w-vl-vr,vh=V.h-vt-vb,vstep=vw/view.length,maxVol=Math.max(...view.map(d=>d.volume||0),1);V.ctx.fillStyle=C.bg;V.ctx.fillRect(0,0,V.w,V.h);V.ctx.strokeStyle=C.grid;V.ctx.fillStyle=C.text;V.ctx.font='10px system-ui';for(let i=0;i<=2;i++){const yy=vt+i*vh/2,val=maxVol-i*maxVol/2;V.ctx.beginPath();V.ctx.moveTo(vl,yy);V.ctx.lineTo(V.w-vr,yy);V.ctx.stroke();V.ctx.fillText(fmtVol(val),V.w-vr+7,yy+4)}view.forEach((d,i)=>{const xx=vl+(i+.5)*vstep,bw=Math.max(2,Math.min(12,vstep*.65)),bar=(d.volume||0)/maxVol*vh;V.ctx.fillStyle=d.close>=d.open?C.up:C.down;V.ctx.globalAlpha=.7;V.ctx.fillRect(xx-bw/2,vt+vh-bar,bw,bar)});V.ctx.globalAlpha=1;if(hover>=b.start&&hover<b.end){const xx=vl+(hover-b.start+.5)*vstep;V.ctx.strokeStyle='#7c8da4';V.ctx.setLineDash([4,4]);V.ctx.beginPath();V.ctx.moveTo(xx,vt);V.ctx.lineTo(xx,vt+vh);V.ctx.stroke();V.ctx.setLineDash([])} }
 function idxAt(ev){const b=bounds(),r=pc.getBoundingClientRect(),l=58,rr=68,w=r.width-l-rr;if(ev.clientX-r.left<l||ev.clientX-r.left>r.width-rr)return-1;return Math.max(b.start,Math.min(b.end-1,b.start+Math.floor((ev.clientX-r.left-l)/w*count)))}
 pc.addEventListener('mousemove',e=>{if(drag){const dx=e.clientX-lastX,last=count/(pc.getBoundingClientRect().width-126),shift=Math.round(-dx*last);if(shift){end+=shift;bounds();lastX=e.clientX;draw()}return}hover=idxAt(e);const d=data[hover];if(d)ro.innerHTML=`${d.date}　O ${d.open.toFixed(2)}　H ${d.high.toFixed(2)}　L ${d.low.toFixed(2)}　C <b>${d.close.toFixed(2)}</b>　量 ${fmtVol(d.volume)}`;draw()});pc.addEventListener('mouseleave',()=>{hover=-1;drag=false;draw()});pc.addEventListener('mousedown',e=>{drag=true;lastX=e.clientX;pc.style.cursor='grabbing'});window.addEventListener('mouseup',()=>{drag=false;pc.style.cursor='crosshair'});pc.addEventListener('wheel',e=>{e.preventDefault();const before=count,count=Math.max(12,Math.min(data.length,Math.round(before*(e.deltaY>0?1.18:.84))));const b=bounds(),r=pc.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(e.clientX-r.left-58)/(r.width-126))),anchor=b.start+Math.round((b.end-b.start)*ratio);end=Math.round(anchor+(1-ratio)*count);bounds();draw()},{passive:false});pc.addEventListener('dblclick',()=>{count=Math.min(132,data.length);end=data.length;draw()});host.querySelectorAll('.range').forEach(btn=>btn.onclick=()=>{count=Math.min(+btn.dataset.n,data.length);end=data.length;draw()});window.addEventListener('resize',draw);draw() }
function renderTech(data,x,meta){const el=$('tvtech');if(!data.length){el.innerHTML='<div class="panel muted">沒有行情。</div>';return}const c=data.map(d=>d.close),last=c.at(-1),avg=n=>c.length>=n?c.slice(-n).reduce((a,b)=>a+b,0)/n:null,m20=avg(20),m50=avg(50),m100=avg(100),m200=avg(200),hi=Math.max(...c.slice(-252)),lo=Math.min(...c.slice(-252)),boxes=[['最新收盤',last?.toFixed(2)],['MA20',m20?.toFixed(2)||'—'],['MA50',m50?.toFixed(2)||'—'],['MA100',m100?.toFixed(2)||'—'],['MA200',m200?.toFixed(2)||'—'],['距52週高',hi?((last/hi-1)*100).toFixed(1)+'%':'—'],['52週位置',hi>lo?((last-lo)/(hi-lo)*100).toFixed(0)+'%':'—'],['趨勢排列',last>m20&&m20>m50&&m50>m100&&m100>m200?'多頭排列':'尚未完整多頭']];el.innerHTML=`<div style="padding:18px"><div class="mini">${boxes.map(a=>`<div class="mb"><small>${a[0]}</small><b>${a[1]}</b></div>`).join('')}</div><div class="foot">行情來源：Yahoo Finance 歷史日資料。均線以收盤價計算。</div></div>`}
async function renderChip(x){const el=$('tvchip');if(x.market!=='TW'){el.innerHTML=`<div class="panel" style="margin:18px"><h3>美股籌碼</h3><p class="muted">美股沒有台股「三大法人 / 主力券商」相同口徑。可改看機構持股、成交量與財報。</p><button class="btn" onclick="window.open('https://finance.yahoo.com/quote/${x.symbol}/holders/','_blank')">Yahoo 機構持股</button></div>`;return}
 el.innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">讀取三大法人資料中…</div>';let institutional='';try{const r=await fetch('https://www.twse.com.tw/rwd/zh/fund/T86?response=json&selectType=ALL',{cache:'no-store'}),j=await r.json(),f=j.fields||[],row=(j.data||[]).find(a=>String(a[0]).trim()===x.symbol);if(row){const get=(keys)=>{for(const k of keys){const i=f.findIndex(v=>v.includes(k));if(i>=0){const z=Number(String(row[i]).replaceAll(',',''));if(Number.isFinite(z))return z}}return null},foreign=get(['外陸資買賣超股數','外資及陸資買賣超股數']),trust=get(['投信買賣超股數']),dealer=get(['自營商買賣超股數']),total=get(['三大法人買賣超股數']),fmt=v=>Number.isFinite(v)?(v/1000).toLocaleString(undefined,{maximumFractionDigits:0})+' 張':'—';institutional=`<div class="mini"><div class="mb"><small>外資買賣超</small><b class="${foreign>0?'good':foreign<0?'bad':''}">${fmt(foreign)}</b></div><div class="mb"><small>投信買賣超</small><b class="${trust>0?'good':trust<0?'bad':''}">${fmt(trust)}</b></div><div class="mb"><small>自營商買賣超</small><b class="${dealer>0?'good':dealer<0?'bad':''}">${fmt(dealer)}</b></div><div class="mb"><small>三大法人合計</small><b class="${total>0?'good':total<0?'bad':''}">${fmt(total)}</b></div></div>`}else institutional='<div class="muted">證交所今日資料尚未找到此股票。</div>'}catch(e){institutional='<div class="muted">證交所法人資料暫時無法載入。</div>'}
 el.innerHTML=`<div style="padding:18px"><h3 style="margin-top:0">三大法人｜最新交易日</h3>${institutional}<div class="card panel" style="margin-top:16px"><h3>主力買賣超 / 券商分點</h3><p class="muted">Yahoo 股市有完整主力買賣超、買超券商與賣超券商排行榜。這類分點資料沒有穩定公開 API，因此直接開 Yahoo 原頁最可靠。</p><p><button class="btn primary" onclick="window.open('https://tw.stock.yahoo.com/quote/${x.symbol}.TW/broker-trading','_blank')">Yahoo 主力進出</button> <button class="btn" onclick="window.open('https://tw.stock.yahoo.com/quote/${x.symbol}.TW/institutional-trading','_blank')">Yahoo 法人買賣</button> <button class="btn" onclick="window.open('https://www.wantgoo.com/stock/${x.symbol}/major-investors/main-trend','_blank')">玩股網籌碼</button></p></div></div>` }
function renderFund(x){if(x.market==='TW'){$('tvprofile').innerHTML=`<div class="panel"><h3>${x.symbol} ${x.name}</h3><p><button class="btn primary" onclick="window.open('https://tw.stock.yahoo.com/quote/${x.symbol}.TW','_blank')">Yahoo 股市</button> <button class="btn" onclick="window.open('https://goodinfo.tw/tw/StockDetail.asp?STOCK_ID=${x.symbol}','_blank')">Goodinfo</button></p></div>`;$('tvfund').innerHTML=`<div class="panel"><h3>財務資料</h3><p class="muted">財報與估值直接開 Yahoo / Goodinfo，避免第三方嵌入限制。</p></div>`}else{$('tvprofile').innerHTML=`<div class="panel"><h3>${x.symbol} ${x.name}</h3><button class="btn primary" onclick="window.open('https://finance.yahoo.com/quote/${x.symbol}/','_blank')">Yahoo Finance</button></div>`;$('tvfund').innerHTML=`<div class="panel"><h3>財務資料</h3><button class="btn" onclick="window.open('https://finance.yahoo.com/quote/${x.symbol}/financials/','_blank')">Yahoo Financials</button></div>`}}
window.detail=async(m,i)=>{const x=watch[m][i];$('mt').textContent=x.symbol;$('mn').textContent=x.name;$('stockModal').classList.add('show');document.body.style.overflow='hidden';document.querySelectorAll('#stockModal .tabs button').forEach((b,j)=>b.classList.toggle('on',j===0));document.querySelectorAll('#stockModal .tabp').forEach((p,j)=>p.classList.toggle('on',j===0));$('tvchart').innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">正在讀取 Yahoo Finance 日 K…</div>';$('tvtech').innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">正在計算 MA20 / 50 / 100 / 200…</div>';$('tvchip').innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">準備籌碼資料…</div>';renderFund(x);renderChip(x);try{const {data,meta}=await fetchYahoo(x);if(!data.length)throw new Error('無日K');renderChart(data,x,meta);renderTech(data,x,meta)}catch(e){$('tvchart').innerHTML=`<div class="panel" style="margin:20px"><h3>Yahoo 行情暫時無法載入</h3><p class="muted">${String(e.message||e)}</p><button class="btn primary" onclick="window.open('${x.market==='TW'?'https://tw.stock.yahoo.com/quote/'+x.symbol+'.TW':'https://finance.yahoo.com/quote/'+x.symbol}/','_blank')">開啟 Yahoo 原頁</button></div>`;$('tvtech').innerHTML='<div class="panel muted" style="margin:20px">行情載入失敗，無法計算均線。</div>'}};
})();