(()=>{
const $=id=>document.getElementById(id);
const oldDetail=window.detail;
const COLORS={bg:'#07111f',text:'#91a4bd',grid:'#1c3048',up:'#ff5d73',down:'#55d6b2',ma20:'#f4ca63',ma50:'#6ea8fe',ma100:'#c084fc',ma200:'#f59e0b'};
let lwPromise=null;
function loadLW(){if(window.LightweightCharts)return Promise.resolve();if(lwPromise)return lwPromise;lwPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js';s.onload=resolve;s.onerror=()=>reject(new Error('圖表元件載入失敗'));document.head.appendChild(s)});return lwPromise}
function n(v){if(v==null)return null;const x=Number(String(v).replaceAll(',','').replace('--',''));return Number.isFinite(x)?x:null}
function rocDateToISO(s){const p=String(s).split('/');if(p.length!==3)return s;return `${Number(p[0])+1911}-${String(p[1]).padStart(2,'0')}-${String(p[2]).padStart(2,'0')}`}
function monthsBack(count=30){const a=[],d=new Date();for(let i=count-1;i>=0;i--){const x=new Date(d.getFullYear(),d.getMonth()-i,1);a.push(`${x.getFullYear()}${String(x.getMonth()+1).padStart(2,'0')}01`)}return a}
async function fetchTWSE(symbol){const all=[];for(const date of monthsBack(30)){try{const u=`https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=${date}&stockNo=${encodeURIComponent(symbol)}&response=json`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)continue;const j=await r.json();if(!Array.isArray(j.data))continue;for(const a of j.data){const row={time:rocDateToISO(a[0]),volume:n(a[1]),open:n(a[3]),high:n(a[4]),low:n(a[5]),close:n(a[6])};if([row.open,row.high,row.low,row.close].every(Number.isFinite))all.push(row)}}catch(e){}}
 const m=new Map();all.forEach(r=>m.set(r.time,r));return [...m.values()].sort((a,b)=>a.time.localeCompare(b.time))}
function moving(data,len){const out=[];let sum=0;for(let i=0;i<data.length;i++){sum+=data[i].close;if(i>=len)sum-=data[i-len].close;if(i>=len-1)out.push({time:data[i].time,value:sum/len})}return out}
function findLegs(x){try{return positions.filter(p=>p.market==='TW'&&p.ticker===x.symbol).flatMap(p=>p.legs.map(l=>({type:l.type,time:(l.at||'').slice(0,10),price:l.price,qty:l.qty}))) }catch{return[]}}
function addLine(chart,data,color,title){const s=chart.addLineSeries({color,lineWidth:2,title,priceLineVisible:false,lastValueVisible:false});s.setData(data);return s}
function renderTWChart(data,x){const host=$('tvchart');host.innerHTML=`<div style="height:100%;display:flex;flex-direction:column"><div style="padding:9px 12px;border-bottom:1px solid #243a55;display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><div><b>${x.symbol} ${x.name||''}</b> <span class="muted">證交所日 K｜可縮放拖曳</span></div><div id="twReadout" style="font-size:12px;color:#b8c7d9">移到 K 棒查看 OHLC</div></div><div style="padding:7px 12px;border-bottom:1px solid #182b42;display:flex;gap:12px;flex-wrap:wrap;font-size:12px"><b style="color:${COLORS.ma20}">MA20</b><b style="color:${COLORS.ma50}">MA50</b><b style="color:${COLORS.ma100}">MA100</b><b style="color:${COLORS.ma200}">MA200</b><span class="muted">滾輪縮放｜拖曳平移｜十字線讀值</span></div><div id="twPriceChart" style="height:510px"></div><div style="padding:5px 12px;color:#91a4bd;font-size:11px;border-top:1px solid #243a55">成交量</div><div id="twVolChart" style="height:175px"></div></div>`;
 const common={layout:{background:{type:'solid',color:COLORS.bg},textColor:COLORS.text},grid:{vertLines:{color:COLORS.grid},horzLines:{color:COLORS.grid}},crosshair:{mode:0},rightPriceScale:{borderColor:'#2a405b'},timeScale:{borderColor:'#2a405b',timeVisible:false,secondsVisible:false},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:false},handleScale:{axisPressedMouseMove:true,mouseWheel:true,pinch:true}};
 const priceChart=LightweightCharts.createChart($('twPriceChart'),{...common,width:$('twPriceChart').clientWidth,height:510});
 const candle=priceChart.addCandlestickSeries({upColor:COLORS.up,downColor:COLORS.down,borderUpColor:COLORS.up,borderDownColor:COLORS.down,wickUpColor:COLORS.up,wickDownColor:COLORS.down});
 candle.setData(data.map(d=>({time:d.time,open:d.open,high:d.high,low:d.low,close:d.close})));
 addLine(priceChart,moving(data,20),COLORS.ma20,'MA20');addLine(priceChart,moving(data,50),COLORS.ma50,'MA50');addLine(priceChart,moving(data,100),COLORS.ma100,'MA100');addLine(priceChart,moving(data,200),COLORS.ma200,'MA200');
 const markers=findLegs(x).map(l=>({time:l.time,position:l.type==='BUY'?'belowBar':'aboveBar',color:l.type==='BUY'?'#22c55e':'#ef4444',shape:l.type==='BUY'?'arrowUp':'arrowDown',text:`${l.type==='BUY'?'買':'賣'} ${l.price||''}`})).filter(m=>data.some(d=>d.time===m.time));if(markers.length)candle.setMarkers(markers);
 const volChart=LightweightCharts.createChart($('twVolChart'),{...common,width:$('twVolChart').clientWidth,height:175});const vol=volChart.addHistogramSeries({priceFormat:{type:'volume'},priceScaleId:''});vol.priceScale().applyOptions({scaleMargins:{top:.08,bottom:0}});vol.setData(data.map(d=>({time:d.time,value:d.volume||0,color:d.close>=d.open?'rgba(255,93,115,.65)':'rgba(85,214,178,.65)'})));
 let syncing=false;priceChart.timeScale().subscribeVisibleLogicalRangeChange(r=>{if(!r||syncing)return;syncing=true;volChart.timeScale().setVisibleLogicalRange(r);syncing=false});volChart.timeScale().subscribeVisibleLogicalRangeChange(r=>{if(!r||syncing)return;syncing=true;priceChart.timeScale().setVisibleLogicalRange(r);syncing=false});
 priceChart.subscribeCrosshairMove(p=>{if(!p?.time)return;const d=p.seriesData.get(candle);if(!d)return;$('twReadout').innerHTML=`${p.time}　O ${d.open.toFixed(2)}　H ${d.high.toFixed(2)}　L ${d.low.toFixed(2)}　C <b>${d.close.toFixed(2)}</b>`});
 const fit=()=>{priceChart.applyOptions({width:$('twPriceChart').clientWidth});volChart.applyOptions({width:$('twVolChart').clientWidth})};window.addEventListener('resize',fit);priceChart.timeScale().fitContent();const bars=Math.min(130,data.length);priceChart.timeScale().setVisibleLogicalRange({from:data.length-bars,to:data.length+4});volChart.timeScale().setVisibleLogicalRange({from:data.length-bars,to:data.length+4});}
function renderTech(data){const c=data.map(d=>d.close),last=c.at(-1),avg=k=>c.length>=k?c.slice(-k).reduce((a,b)=>a+b,0)/k:null,m20=avg(20),m50=avg(50),m100=avg(100),m200=avg(200),hi=Math.max(...c.slice(-252)),lo=Math.min(...c.slice(-252));const boxes=[['最新收盤',last?.toFixed(2)||'—'],['MA20',m20?.toFixed(2)||'—'],['MA50',m50?.toFixed(2)||'—'],['MA100',m100?.toFixed(2)||'—'],['MA200',m200?.toFixed(2)||'—'],['距52週高',hi?((last/hi-1)*100).toFixed(1)+'%':'—'],['52週位置',hi>lo?((last-lo)/(hi-lo)*100).toFixed(0)+'%':'—'],['均線排列',last>m20&&m20>m50&&m50>m100&&m100>m200?'完整多頭':'未完整多頭']];$('tvtech').innerHTML=`<div style="padding:18px"><div class="mini">${boxes.map(a=>`<div class="mb"><small>${a[0]}</small><b>${a[1]}</b></div>`).join('')}</div><div class="foot">資料來源：臺灣證券交易所；均線以日收盤價計算。</div></div>`}
async function renderChip(x){const el=$('tvchip');el.innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">讀取三大法人資料中…</div>';let body='';try{const r=await fetch('https://www.twse.com.tw/rwd/zh/fund/T86?response=json&selectType=ALL',{cache:'no-store'}),j=await r.json(),f=j.fields||[],row=(j.data||[]).find(a=>String(a[0]).trim()===x.symbol);const get=keys=>{for(const k of keys){const i=f.findIndex(v=>String(v).includes(k));if(i>=0){const z=n(row?.[i]);if(Number.isFinite(z))return z}}return null},fmt=v=>Number.isFinite(v)?(v/1000).toLocaleString(undefined,{maximumFractionDigits:0})+' 張':'—',foreign=get(['外陸資買賣超股數','外資及陸資買賣超股數']),trust=get(['投信買賣超股數']),dealer=get(['自營商買賣超股數']),total=get(['三大法人買賣超股數']);body=`<div class="mini"><div class="mb"><small>外資買賣超</small><b class="${foreign>0?'good':foreign<0?'bad':''}">${fmt(foreign)}</b></div><div class="mb"><small>投信買賣超</small><b class="${trust>0?'good':trust<0?'bad':''}">${fmt(trust)}</b></div><div class="mb"><small>自營商買賣超</small><b class="${dealer>0?'good':dealer<0?'bad':''}">${fmt(dealer)}</b></div><div class="mb"><small>三大法人合計</small><b class="${total>0?'good':total<0?'bad':''}">${fmt(total)}</b></div></div>`}catch(e){body='<div class="muted">三大法人資料暫時無法取得。</div>'}el.innerHTML=`<div style="padding:18px"><h3>法人籌碼</h3>${body}<div class="callout" style="margin-top:18px"><b>主力 / 券商分點：</b>券商分點並沒有適合直接嵌入本站、且穩定的免費官方即時 API，因此不硬抓不穩定來源。下面直接開該股分點頁，避免錯誤資料。</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" onclick="window.open('https://www.wantgoo.com/stock/${x.symbol}/major-investors/main-trend','_blank')">玩股網主力</button><button class="btn" onclick="window.open('https://goodinfo.tw/tw/ShowBuySaleChart.asp?STOCK_ID=${x.symbol}','_blank')">Goodinfo 買賣超</button><button class="btn" onclick="window.open('https://tw.stock.yahoo.com/quote/${x.symbol}.TW/broker-trading','_blank')">Yahoo 主力進出</button></div></div>`}
function renderFund(x){$('tvprofile').innerHTML=`<div class="panel"><h3>${x.symbol} ${x.name}</h3><p><button class="btn" onclick="window.open('https://goodinfo.tw/tw/StockDetail.asp?STOCK_ID=${x.symbol}','_blank')">Goodinfo</button> <button class="btn" onclick="window.open('https://tw.stock.yahoo.com/quote/${x.symbol}.TW','_blank')">Yahoo 股市</button></p></div>`;$('tvfund').innerHTML=`<div class="panel"><h3>公司與財報</h3><p class="muted">基本面先保留可靠外部來源，K 線與法人籌碼則直接留在 TradeLab。</p></div>`}
window.detail=async(m,i)=>{if(m==='US')return oldDetail(m,i);const x=watch[m][i];$('mt').textContent=x.symbol;$('mn').textContent=x.name;$('stockModal').classList.add('show');document.body.style.overflow='hidden';document.querySelectorAll('#stockModal .tabs button').forEach((b,j)=>b.classList.toggle('on',j===0));document.querySelectorAll('#stockModal .tabp').forEach((p,j)=>p.classList.toggle('on',j===0));$('tvchart').innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">正在讀取證交所行情…</div>';$('tvtech').innerHTML='<div style="display:grid;place-items:center;height:100%;color:#91a4bd">正在計算技術面…</div>';renderFund(x);renderChip(x);try{await loadLW();const data=await fetchTWSE(x.symbol);if(!data.length)throw new Error('沒有行情資料');renderTWChart(data,x);renderTech(data)}catch(e){$('tvchart').innerHTML=`<div class="panel" style="margin:18px"><h3>台股圖表載入失敗</h3><p class="muted">${e.message||e}</p><button class="btn" onclick="window.open('https://www.wantgoo.com/stock/${x.symbol}','_blank')">開啟玩股網</button></div>`;$('tvtech').innerHTML='<div class="panel muted" style="margin:18px">技術資料暫時無法載入。</div>'}};
})();